import Stripe from 'stripe'

export function isStripeConfigured(): boolean {
  const key = process.env.STRIPE_SECRET_KEY
  return !!key && key !== 'placeholder' && !key.includes('placeholder')
}

export function getStripeClient(): Stripe {
  return new Stripe(process.env.STRIPE_SECRET_KEY!, {
    apiVersion: '2025-02-24.acacia',
  })
}

export const PRICES = {
  standard: 4700,    // $47.00 in cents
  subscriber: 3700,  // $37.00 for newsletter subscribers
} as const

/**
 * Creates a Stripe Checkout session.
 * Returns the session URL to redirect the user to.
 */
export async function createCheckoutSession({
  assessmentId,
  email,
  isSubscriber,
  appUrl,
  archetypeName = '',
}: {
  assessmentId: string
  email: string
  isSubscriber: boolean
  appUrl: string
  archetypeName?: string
}): Promise<string> {
  const amount = isSubscriber ? PRICES.subscriber : PRICES.standard

  const session = await getStripeClient().checkout.sessions.create({
    payment_method_types: ['card'],
    mode: 'payment',
    customer_email: email,
    line_items: [
      {
        price_data: {
          currency: 'usd',
          unit_amount: amount,
          product_data: {
            name: 'The Noble Compass — Your Personal Sales Playbook',
            description:
              'Your custom 6-section Noble Compass, generated by AI from your Noble Quotient assessment results.',
            images: [],
          },
        },
        quantity: 1,
      },
    ],
    metadata: {
      assessment_id: assessmentId,
      archetype_name: archetypeName,
    },
    success_url: `${appUrl}/codex/${assessmentId}?session_id={CHECKOUT_SESSION_ID}`,
    cancel_url: `${appUrl}/quotient/results/${assessmentId}?canceled=true`,
  })

  if (!session.url) throw new Error('Stripe did not return a checkout URL')
  return session.url
}
